### ISSUE TITLE
Error "Stream no yet started! Stream start: Web, 18:30" on already available videos

### ISSUE THREAD

**Issue by Tumbleweeds** [stipx/plugin.video.laola1free#9]
I noticed some handball videos get this error now (I didn't try other sports). It was working 2 or 3 weeks ago when I last tested. Looks like videos that play on the laola1 site are ok, but the ones redirected to ehftv.com are the problem.

Thanks for keeping this plugin alive!

﻿16:39:05.168 T:1106625952  NOTICE: special://profile/ is mapped to: special://masterprofile/
16:39:05.168 T:1106625952  NOTICE: -----------------------------------------------------------------------
16:39:05.168 T:1106625952  NOTICE: Starting Kodi (17.1-RC1 Git:20170223-1a80820). Platform: Android ARM 32-bit
16:39:05.169 T:1106625952  NOTICE: Using Release Kodi x32 build
16:39:05.169 T:1106625952  NOTICE: Kodi compiled Feb 23 2017 by GCC 4.9.0 for Android ARM 32-bit API level 21 (API level 21)
16:39:05.170 T:1106625952  NOTICE: Running on Amazon AFTM with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.0.31+
16:39:05.171 T:1106625952  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
16:39:05.171 T:1106625952  NOTICE: Host CPU: ARMv7 Processor rev 0 (v7l), 2 cores available
16:39:05.171 T:1106625952  NOTICE: Product: montoya, Device: montoya, Board: capri - Manufacturer: Amazon, Brand: Amazon, Model: AFTM, Hardware: montoya
16:39:05.173 T:1106625952  NOTICE: External storage path = /storage/emulated/0; status = ok
16:39:05.174 T:1106625952  NOTICE: ARM Features: Neon enabled
16:39:05.174 T:1106625952  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
16:39:05.174 T:1106625952  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
16:39:05.174 T:1106625952  NOTICE: special://xbmcbinaddons/ is mapped to: /data/app/org.xbmc.kodi-1/lib/arm
16:39:05.174 T:1106625952  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
16:39:05.174 T:1106625952  NOTICE: special://envhome/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files
16:39:05.175 T:1106625952  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
16:39:05.175 T:1106625952  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
16:39:05.175 T:1106625952  NOTICE: special://logpath/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
16:39:05.175 T:1106625952  NOTICE: The executable running is: /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so
16:39:05.176 T:1106625952  NOTICE: Local hostname: localhost
16:39:05.176 T:1106625952  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp//kodi.log
16:39:05.176 T:1106625952  NOTICE: -----------------------------------------------------------------------
16:39:05.206 T:1106625952  NOTICE: load settings...
16:39:05.288 T:1106625952   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
16:39:05.293 T:1106625952 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
16:39:05.328 T:1106625952   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
16:39:05.332 T:1106625952   DEBUG: Firmware implements AC3 RAW
16:39:05.332 T:1106625952   DEBUG: Firmware implements EAC3 RAW
16:39:05.335 T:1106625952   DEBUG: AESinkAUDIOTRACK - 32000 supported
16:39:05.336 T:1106625952   DEBUG: AESinkAUDIOTRACK - 44100 supported
16:39:05.338 T:1106625952   DEBUG: AESinkAUDIOTRACK - 48000 supported
16:39:05.339 T:1106625952   DEBUG: AESinkAUDIOTRACK - 88200 supported
16:39:05.339 T:1106625952   DEBUG: AESinkAUDIOTRACK - 96000 supported
16:39:05.340 T:1106625952  NOTICE: Found 1 Lists of Devices
16:39:05.340 T:1106625952  NOTICE: Enumerated AUDIOTRACK devices:
16:39:05.340 T:1106625952  NOTICE:     Device 1
16:39:05.344 T:1106625952  NOTICE:         m_deviceName      : AudioTrack
16:39:05.344 T:1106625952  NOTICE:         m_displayName     : android
16:39:05.344 T:1106625952  NOTICE:         m_displayNameExtra: audiotrack
16:39:05.344 T:1106625952  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
16:39:05.344 T:1106625952  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR,SL,SR
16:39:05.344 T:1106625952  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000
16:39:05.344 T:1106625952  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_RAW
16:39:05.345 T:1106625952  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_EAC3
16:39:05.366 T:1106625952   DEBUG: CSkinSettings: no <skinsettings> tag found
16:39:05.366 T:1106625952  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
16:39:05.369 T:1106625952  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
16:39:05.370 T:1106625952   DEBUG: Configuring path substitutions
16:39:05.370 T:1106625952   DEBUG:   Registering substition pair:
16:39:05.370 T:1106625952   DEBUG:     From: [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/playlists/]
16:39:05.371 T:1106625952   DEBUG:     To:   [NFS://192.168.1.31/mnt/tank/Kodi/userdata/playlists/]
16:39:05.371 T:1106625952   DEBUG:   Registering substition pair:
16:39:05.371 T:1106625952   DEBUG:     From: [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/sources.xml]
16:39:05.371 T:1106625952   DEBUG:     To:   [NFS://192.168.1.31/mnt/tank/Kodi/userdata/sources.xml]
16:39:05.371 T:1106625952   DEBUG:   Registering substition pair:
16:39:05.371 T:1106625952   DEBUG:     From: [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/favourites.xml]
16:39:05.372 T:1106625952   DEBUG:     To:   [NFS://192.168.1.31/mnt/tank/Kodi/userdata/favourites.xml]
16:39:05.372 T:1106625952   DEBUG:   Registering substition pair:
16:39:05.372 T:1106625952   DEBUG:     From: [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/passwords.xml]
16:39:05.372 T:1106625952   DEBUG:     To:   [NFS://192.168.1.31/mnt/tank/Kodi/userdata/passwords.xml]
16:39:05.372 T:1106625952 WARNING: VIDEO database configuration is experimental.
16:39:05.374 T:1106625952  NOTICE: Default Video Player: VideoPlayer
16:39:05.374 T:1106625952  NOTICE: Default Audio Player: paplayer
16:39:05.374 T:1106625952  NOTICE: Disabled debug logging due to GUI setting. Level 0.
16:39:05.375 T:1106625952  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
16:39:05.438 T:1106625952  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
16:39:05.457 T:1106625952  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
16:39:05.464 T:1106625952  NOTICE: Loaded playercorefactory configuration
16:39:05.465 T:1106625952  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
16:39:05.466 T:1106625952  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
16:39:05.539 T:1106625952  NOTICE: Running database version Addons27
16:39:05.917 T:1106625952  NOTICE: ADDONS: Using repository repository.xbmc.org
16:39:06.105 T:1109007296  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
16:39:06.118 T:1109007296  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 42336 m_frames: 2646 m_frameSize: 8 channels: 2
16:39:06.262 T:1106625952  NOTICE: InitWindowSystem: Using EGL Implementation: android
16:39:06.362 T:1106625952  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
16:39:06.363 T:1106625952  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
16:39:06.363 T:1106625952  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
16:39:06.364 T:1106625952  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
16:39:06.364 T:1106625952  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
16:39:06.364 T:1106625952  NOTICE: Found (1280x720@60.000000) at 16, setting to RES_DESKTOP at 16
16:39:06.364 T:1106625952  NOTICE: Checking resolution 16
16:39:06.380 T:1106625952  NOTICE: GL_VENDOR = Broadcom
16:39:06.380 T:1106625952  NOTICE: GL_RENDERER = VideoCore IV HW
16:39:06.380 T:1106625952  NOTICE: GL_VERSION = OpenGL ES 2.0
16:39:06.381 T:1106625952  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
16:39:06.381 T:1106625952  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker
16:39:06.382 T:1109007296  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding
16:39:06.403 T:1109007296  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 42336 m_frames: 2646 m_frameSize: 8 channels: 2
16:39:08.493 T:1108921376  NOTICE: Running database version Addons27
16:39:08.680 T:1108921376  NOTICE: Running database version ViewModes6
16:39:08.688 T:1108921376  NOTICE: Running database version Textures13
16:39:08.770 T:1108921376  NOTICE: Running database version MyMusic60
16:39:08.794 T:1108921376  NOTICE: Running database version MyVideos107
16:39:08.814 T:1108921376  NOTICE: Running database version TV29
16:39:08.833 T:1108921376  NOTICE: Running database version Epg11
16:39:10.127 T:1106625952 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
16:39:11.860 T:1106625952  NOTICE: initialize done
16:39:11.861 T:1106625952  NOTICE: Running the application...
16:39:11.905 T:1106625952  NOTICE: starting upnp client
16:39:11.947 T:1391826880  NOTICE: ES: Starting UDP Event server on port 9777
16:39:11.951 T:1391826880  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
16:39:11.951 T:1106625952  NOTICE: GL_VENDOR = Broadcom
16:39:11.952 T:1106625952  NOTICE: GL_RENDERER = VideoCore IV HW
16:39:11.952 T:1106625952  NOTICE: GL_VERSION = OpenGL ES 2.0
16:39:11.952 T:1106625952  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
16:39:11.952 T:1106625952  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker
16:39:28.999 T:1108921376  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
16:39:33.028 T:1396409704   ERROR: GetDirectory - Error getting
16:39:34.046 T:1401965472   ERROR: Previous line repeats 6 times.
16:39:34.047 T:1401965472  NOTICE: NOTICE - Debug logging enabled: True
16:39:34.047 T:1401965472  NOTICE: INFO - Starting addon with ['plugin://plugin.video.laola1free/', '1', '?id=2-4-0-0&type=block&url=http%3a%2f%2fwww.laola1.tv%2fen-int%2fblock%2fhandball-latest-videos']
16:39:34.047 T:1401965472  NOTICE: INFO - Python version: 2.7.12
16:39:34.051 T:1401965472  NOTICE: DEBUG - Load block from "http://www.laola1.tv/en-int/block/handball-latest-videos"
16:39:34.052 T:1401965472  NOTICE: DEBUG - Block: {'url': 'http://www.laola1.tv/en-int/block/handball-latest-videos'}
16:39:34.615 T:1401965472  NOTICE: DEBUG - HTML data length stripping - before: 144739 - after: 14846
16:39:44.227 T:1417210264  NOTICE: NOTICE - Debug logging enabled: True
16:39:44.227 T:1417210264  NOTICE: INFO - Starting addon with ['plugin://plugin.video.laola1free/', '2', '?url=http%3A%2F%2Fwww.laola1.tv%2Fen-int%2Fvideo%2Fbest-7-group-b-len&type=video']
16:39:44.227 T:1417210264  NOTICE: INFO - Python version: 2.7.12
16:39:44.229 T:1417210264  NOTICE: INFO - Get videoplayer url from "http://www.laola1.tv/en-int/video/best-7-group-b-len"
16:39:53.017 T:1106625952  NOTICE: VideoPlayer: Opening:
16:39:53.017 T:1106625952 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:39:53.018 T:1417508384  NOTICE: Creating InputStream
16:39:53.019 T:1417508384   ERROR: CVideoPlayer::OpenInputStream - error opening []
16:39:53.019 T:1417508384  NOTICE: CVideoPlayer::OnExit()
16:39:53.079 T:1106625952   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.laola1free/?url=http%3A%2F%2Fwww.laola1.tv%2Fen-int%2Fvideo%2Fbest-7-group-b-len&type=video]
16:39:53.108 T:1106625952  NOTICE: CVideoPlayer::CloseFile()
16:39:53.108 T:1106625952  NOTICE: VideoPlayer: waiting for threads to exit
16:39:53.108 T:1106625952  NOTICE: VideoPlayer: finished waiting
16:39:53.109 T:1106625952  NOTICE: CVideoPlayer::CloseFile()
16:39:53.109 T:1106625952  NOTICE: VideoPlayer: waiting for threads to exit
16:39:53.109 T:1106625952  NOTICE: VideoPlayer: finished waiting
16:41:02.396 T:1106625952  NOTICE: NFS is idle. Closing the remaining connections.

**Comment by stipx** [comment]
Handball streams are always a bit special. ehftv.com changed the way they include the videoplayer

This is fixed now.
